### ISSUE TITLE
Better documentation needed for components

### ISSUE THREAD

**Issue by cyberprodigy** [Fitbit/sdk-design-assets#6]
This link https://dev.fitbit.com/build/guides/design-guidelines/ui-components/#tumbler says
All of these components are available in a Sketch file in Downloads.

The link points to this repository.

There is indeed a file with extension .sketch but nowhere is explained how to view the file.

There should be explanation on how to view .sketch, since it's a binary and nothing useful shows if opened in text editor.

**Comment by orviwan** [comment]
You need the Sketch app to view this file. https://www.sketchapp.com
