### ISSUE TITLE
Battery Icon

### ISSUE THREAD

**Issue by daveyjones** [Fitbit/sdk-design-assets#7]
A battery indicator is a common request on clock faces—is there any way that could be included in these assets?

**Comment by daveyjones** [comment]
One more note on the battery icon—ideally it would be identical to the OS icon so we can position it in a way that will allow it to transition seamlessly when the OS icon is displayed.

**Comment by swlaing** [comment]
Here are the files that were included in the Fitbit OS emulator. Hopefully that helps.

![battery_small_red](https://user-images.githubusercontent.com/46271152/50552620-2c8a4480-0c65-11e9-9b81-e8216297822e.png)
![battery_charging_step](https://user-images.githubusercontent.com/46271152/50552621-2c8a4480-0c65-11e9-8e72-84eebf94c24d.png)
![battery_small_00](https://user-images.githubusercontent.com/46271152/50552622-2c8a4480-0c65-11e9-918b-f8c62927b215.png)
![battery_small_01](https://user-images.githubusercontent.com/46271152/50552623-2c8a4480-0c65-11e9-827c-4febddfbdba9.png)
![battery_small_02](https://user-images.githubusercontent.com/46271152/50552624-2c8a4480-0c65-11e9-84f7-4f20afbdda83.png)
![battery_small_03](https://user-images.githubusercontent.com/46271152/50552625-2c8a4480-0c65-11e9-8f6e-d742e7ddfeeb.png)
![battery_small_blue](https://user-images.githubusercontent.com/46271152/50552626-2c8a4480-0c65-11e9-9df8-b77394f290c6.png)
![battery_small_container](https://user-images.githubusercontent.com/46271152/50552627-2c8a4480-0c65-11e9-94f0-9339ddd867e0.png)
![battery_small_gray](https://user-images.githubusercontent.com/46271152/50552628-2d22db00-0c65-11e9-936b-9d7a296d6cd3.png)
![battery_small_green](https://user-images.githubusercontent.com/46271152/50552629-2d22db00-0c65-11e9-91e7-9d24a6df52d9.png)
